# Generated by Django 6.0.3 on 2026-03-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("placements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("activities", models.TextField()),
                ("challenges", models.TextField()),
                ("learnings", models.TextField()),
                ("attachments_url", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=255)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="placements.internshipplacements",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupervisorReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("decision", models.CharField(max_length=255)),
                ("comment", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
                (
                    "weekly_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logbook.weeklylogs"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyLogStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_status", models.CharField(max_length=255)),
                ("to_status", models.CharField(max_length=255)),
                ("comment", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
                (
                    "weekly_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logbook.weeklylogs"
                    ),
                ),
            ],
        ),
    ]
