# Generated by Django 6.0.3 on 2026-03-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
        ("placements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRubrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academics.institutions"
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academics.programmes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("max_score", models.IntegerField()),
                ("weight_percent", models.FloatField()),
                ("evaluator_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluationrubrics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("evaluator_type", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("total_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="placements.internshipplacements",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluationrubrics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score", models.FloatField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.evaluationcriteria",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="evaluations.evaluations"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("logbook_score", models.FloatField()),
                ("workplace_score", models.FloatField()),
                ("academic_score", models.FloatField()),
                ("final_score", models.FloatField()),
                ("final_grade", models.CharField(max_length=255)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="placements.internshipplacements",
                    ),
                ),
            ],
        ),
    ]
