# Generated by Django 6.0.3 on 2026-03-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evaluationcriteria",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="finalresults",
            name="workplace_score",
        ),
        migrations.AddField(
            model_name="evaluationcriteria",
            name="group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="evaluationcriteria",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evaluationrubrics",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evaluationrubrics",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evaluationrubrics",
            name="version",
            field=models.CharField(default="1.0", max_length=32),
        ),
        migrations.AddField(
            model_name="evaluations",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="evaluationscores",
            name="is_finalized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="finalresults",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finalresults",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="evaluations.evaluationrubrics",
            ),
        ),
        migrations.AddField(
            model_name="finalresults",
            name="workplace_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evaluationcriteria",
            name="evaluator_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("workplace_supervisor", "Workplace Supervisor"),
                    ("academic_supervisor", "Academic Supervisor"),
                    ("internship_admin", "Internship Administrator"),
                ],
                default="academic_supervisor",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="evaluator_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("workplace_supervisor", "Workplace Supervisor"),
                    ("academic_supervisor", "Academic Supervisor"),
                    ("internship_admin", "Internship Administrator"),
                ],
                default="academic_supervisor",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("submitted", "Submitted"), ("reviewed", "Reviewed")],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluationcriteria",
            unique_together={("rubric", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="evaluationscores",
            unique_together={("evaluation", "criterion")},
        ),
    ]
