# Generated by Django 6.0.4 on 2026-04-29 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_remove_departments_institution_colleges_and_more"),
        ("evaluations", "0002_alter_evaluationcriteria_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationrubrics",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.institutions",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationrubrics",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.programmes",
            ),
        ),
    ]
