# Generated by Django 6.0.4 on 2026-04-29 20:11

from django.db import migrations


def create_global_rubric(apps, schema_editor):
    EvaluationRubrics = apps.get_model("evaluations", "EvaluationRubrics")
    EvaluationCriteria = apps.get_model("evaluations", "EvaluationCriteria")

    # Create global rubric
    rubric, created = EvaluationRubrics.objects.get_or_create(
        institution=None,
        programme=None,
        name="Default Final Evaluation Rubric",
        defaults={
            "description": "Global default rubric for final evaluations",
            "version": "1.0",
            "is_current": True,
            "is_active": True,
        },
    )

    # Create default criteria
    criteria = [
        {
            "name": "Technical Skills",
            "description": "Ability to apply technical knowledge to tasks.",
            "order": 1,
            "max_score": 100,
            "weight_percent": 30.0,
            "evaluator_type": "academic_supervisor",
        },
        {
            "name": "Communication Skills",
            "description": "Effectiveness in verbal and written communication.",
            "order": 2,
            "max_score": 100,
            "weight_percent": 20.0,
            "evaluator_type": "academic_supervisor",
        },
        {
            "name": "Problem Solving",
            "description": "Ability to identify problems and propose solutions.",
            "order": 3,
            "max_score": 100,
            "weight_percent": 25.0,
            "evaluator_type": "academic_supervisor",
        },
        {
            "name": "Professionalism & Ethics",
            "description": "Adherence to professional standards and ethical behavior.",
            "order": 4,
            "max_score": 100,
            "weight_percent": 25.0,
            "evaluator_type": "academic_supervisor",
        },
    ]

    for c in criteria:
        EvaluationCriteria.objects.get_or_create(rubric=rubric, name=c["name"], defaults=c)


def remove_global_rubric(apps, schema_editor):
    EvaluationRubrics = apps.get_model("evaluations", "EvaluationRubrics")
    EvaluationRubrics.objects.filter(
        institution=None, programme=None, name="Default Final Evaluation Rubric"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0003_alter_evaluationrubrics_institution_and_more"),
    ]

    operations = [
        migrations.RunPython(create_global_rubric, remove_global_rubric),
    ]
