# Generated by Django 6.0.4 on 2026-05-01 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_remove_departments_institution_colleges_and_more"),
        ("evaluations", "0004_auto_20260429_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluations",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.colleges",
            ),
        ),
        migrations.AddField(
            model_name="finalresults",
            name="college",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.colleges",
            ),
        ),
    ]
