# Generated by Django 6.0.3 on 2026-03-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationAttempts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("webmail", models.EmailField(max_length=254)),
                ("student_number", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                ("otp_hash", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academics.institutions"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("student_number", models.IntegerField()),
                ("webmail", models.EmailField(max_length=254)),
                ("year_of_study", models.IntegerField()),
                ("intake_year", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                ("is_claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academics.institutions"
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="academics.programmes"
                    ),
                ),
            ],
        ),
    ]
