# Generated by Django 6.0.3 on 2026-04-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationattempts",
            name="student_number",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="studentregistry",
            name="intake_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentregistry",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.programmes",
            ),
        ),
        migrations.AlterField(
            model_name="studentregistry",
            name="status",
            field=models.CharField(blank=True, default="active", max_length=255),
        ),
        migrations.AlterField(
            model_name="studentregistry",
            name="student_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentregistry",
            name="year_of_study",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
