# Generated by Django 6.0.2 on 2026-04-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationattempts",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registrationattempts",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registrationattempts",
            name="password_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="studentregistry",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentregistry",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
    ]
