# Generated by Django 6.0.3 on 2026-04-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_alter_registrationattempts_student_number_and_more"),
        ("registry", "0002_registrationattempts_first_name_and_more"),
    ]

    operations = []
