# Generated by Django 6.0.3 on 2026-04-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0003_merge_20260413_2006"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegistrationAttempts",
        ),
    ]
