# Generated by Django 6.0.2 on 2026-04-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_supervisorapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="student_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
