# Generated by Django 6.0.2 on 2026-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_student_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="student_registry_id",
        ),
        migrations.AddField(
            model_name="user",
            name="intake_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="year_of_study",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
