# Generated by Django 4.2.30 on 2026-05-02 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_colleges_id_alter_departments_id_and_more'),
        ('accounts', '0006_remove_user_student_registry_id_user_intake_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorapplication',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.colleges'),
        ),
        migrations.AlterField(
            model_name='staffprofiles',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supervisorapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
