# Generated by Django 4.2.30 on 2026-04-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = []
