# Generated by Django 4.2.30 on 2026-05-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_departments_institution_colleges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='programmes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
